version: '3'
services:
  eth:
    container_name: geth-dev-chain
    build: monitored-geth-client
    restart: on-failure
    links:
      - netstats
    entrypoint: /root/start.sh
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/.ethereum/devchain/keystore:rw
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8545:8545"
