version: '3'
services:
  eth:
    container_name: geth-miner
    build: monitored-geth-client
    restart: on-failure
    links:
      - netstats
    entrypoint: /root/start.sh
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/genesis.json:/root/files/genesis.json:ro
      - ./files/keystore:/root/.ethereum/devchain/keystore:rw
      - /etc/localtime:/etc/localtime:ro
    command: '--dev --dev.period 10'
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"
  netstats:
    build: eth-netstats
    restart: on-failure
    container_name: geth-netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
